#!/usr/bin/env node
/*
  Build vocab-data.js for the web app from YAML in data/v2/.

  - Reads YAML files under HebrewHandwritingWeb/data/v2/{nouns,verbs,adjectives,adverbs,pronouns,prepositions}
  - Extracts a flat list of { he, en, pos }
  - De-duplicates by Hebrew spelling
  - Writes HebrewHandwritingWeb/data/vocab-data.js as a global: window.VOCAB_WORDS = [...]

  Note: This script depends on the 'yaml' package available in the sibling
  hebrew_drills project. No install is needed as long as that folder is present.
*/

const fs = require('fs');
const path = require('path');
const { createRequire } = require('module');

const requireFromHere = createRequire(__filename);
// Resolve the yaml module from the sibling hebrew_drills project
const YAML = requireFromHere('../../hebrew_drills/node_modules/yaml');

const ROOT = path.resolve(__dirname, '..');
const V2_DIR = path.join(ROOT, 'data', 'v2');
const OUT_JS = path.join(ROOT, 'data', 'vocab-data.js');
const OUT_JSON = path.join(ROOT, 'data', 'vocab_words.json');

function listYamlFiles(dir, opts = {}) {
  const { includeAll = true } = opts;
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  const files = [];
  for (const ent of entries) {
    if (!ent.isFile()) continue;
    if (!ent.name.endsWith('.yaml')) continue;
    if (!includeAll && ent.name === 'all.yaml') continue;
    files.push(path.join(dir, ent.name));
  }
  return files;
}

function extractWord(pos, entry) {
  // Normalize pos names to singular for reporting
  const normPos = String(pos || '').trim();
  const gloss = entry.gloss || entry.label || null;
  let he = null;
  switch (normPos) {
    case 'noun':
      he = (entry.forms && (entry.forms.sg || entry.forms.base)) || entry.lemma || null;
      break;
    case 'adjective':
      he = (entry.forms && (entry.forms.m_sg || entry.forms.base)) || entry.lemma || null;
      break;
    case 'verb':
    case 'adverb':
    case 'pronoun':
    case 'preposition':
      he = entry.lemma || null;
      break;
    default:
      he = entry.lemma || null;
  }
  if (!he || !gloss) return null;
  return { he, en: String(gloss), pos: normPos };
}

function readYaml(fp) {
  const src = fs.readFileSync(fp, 'utf8');
  try {
    return YAML.parse(src);
  } catch (err) {
    throw new Error(`Failed parsing YAML: ${fp}: ${err.message}`);
  }
}

function build() {
  const coreOnly = process.argv.includes('--core-only');
  if (!fs.existsSync(V2_DIR)) {
    throw new Error(`Missing data directory: ${V2_DIR}`);
  }

  const posDirs = fs.readdirSync(V2_DIR, { withFileTypes: true })
    .filter(d => d.isDirectory())
    .map(d => d.name)
    // Skip concepts (different shape)
    .filter(name => name !== 'concepts');

  const seen = new Set();
  const words = [];

  for (const dirName of posDirs) {
    const dirPath = path.join(V2_DIR, dirName);
    for (const file of listYamlFiles(dirPath, { includeAll: !coreOnly })) {
      const doc = readYaml(file);
      const filePos = doc && (doc.pos || dirName.replace(/s$/, ''));
      const entries = (doc && Array.isArray(doc.entries)) ? doc.entries : [];
      for (const e of entries) {
        const w = extractWord(filePos, e);
        if (!w) continue;
        if (seen.has(w.he)) continue;
        seen.add(w.he);
        words.push(w);
      }
    }
  }

  // Sort Hebrew words in a stable but simple way (by Unicode code points)
  words.sort((a, b) => a.he.localeCompare(b.he));

  // Write JS global for use by index.html without fetch()
  const header = '// AUTO-GENERATED by scripts/build_vocab.js — do not edit by hand\n';
  const js = `${header}window.VOCAB_WORDS = ${JSON.stringify(words, null, 2)};\n`;
  fs.writeFileSync(OUT_JS, js, 'utf8');

  // Also write pure JSON for other tooling
  fs.writeFileSync(OUT_JSON, JSON.stringify(words, null, 2), 'utf8');

  console.log(`Wrote ${words.length} words to:`);
  console.log(`- ${path.relative(ROOT, OUT_JS)}`);
  console.log(`- ${path.relative(ROOT, OUT_JSON)}`);
}

if (require.main === module) {
  try {
    build();
  } catch (err) {
    console.error(err.message || String(err));
    process.exit(1);
  }
}
